name = "test_19"
uuid = "3cce5eef-6229-42f5-8b2c-011bb87f715a"
authors = ["SmarterMaterials <pro.adrienclavel@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
